modLoader="javafml" 
loaderVersion="${loader_version_range}" 
license="${mod_license}"
issueTrackerURL="https://github.com/simon-mc28/Better-McDonalds-Mod-NeoForge/issues"
[[mods]] 
modId="${mod_id}" 
version="${mod_version}" 
displayName="${mod_name}" 
displayURL="https://www.curseforge.com/minecraft/mc-mods/better-mcdonalds-mod"
logoFile="logo.png"
credits="${mod_credits}"
authors="${mod_authors}" 
description='''${mod_description}'''
[[dependencies.${mod_id}]] 
    modId="forge" 
    mandatory=true 
    versionRange="${neo_version_range}" 
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"